"use client";
import { useRef, useState } from "react";
import {
  Room,
  RemoteAudioTrack,
  RoomEvent,
  RoomConnectOptions,
  createLocalAudioTrack,
} from "livekit-client";

export default function Home() {
  const [room, setRoom] = useState<Room | null>(null);
  const [status, setStatus] = useState<
    "idle" | "connecting" | "connected" | "disconnected"
  >("idle");
  const [micOn, setMicOn] = useState(false);
  const [error, setError] = useState("");

  // Used to play back the voice output generated by the AI
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const startConversation = async () => {
    setStatus("connecting");
    setError("");

    try {
      // Request token API
      const res = await fetch("https://api.jasonchangstudio.com/token");
      if (!res.ok) throw new Error("Failed to get token");

      const { token, url } = await res.json();

      // Create a LiveKit room
      const newRoom = new Room({
        adaptiveStream: true,
        dynacast: true,
      });

      // Listen to AI track
      newRoom.on(RoomEvent.TrackSubscribed, async (track, publication, participant) => {
        console.log("AI Audio Track Subscribed:", participant.identity);

        if (track.kind === "audio") {
          const audioTrack = track as RemoteAudioTrack;

          // <audio> element
          const audioEl = audioTrack.attach();

          audioEl.autoplay = true;   // Auto play the audio
          audioEl.muted = false;

          if (audioRef.current) {
            audioRef.current.srcObject = audioEl.srcObject;
          }

          console.log("Audio attached and ready to play");
        }
      });

      newRoom.on(RoomEvent.TrackUnsubscribed, () => {
        console.log("Track unsubscribed (AI stop talking)");
      });

      newRoom.on(RoomEvent.Connected, () => setStatus("connected"));
      newRoom.on(RoomEvent.Disconnected, () => {
        setStatus("disconnected");
        setMicOn(false);
      });

      // Connect to LiveKit room
      await newRoom.connect(url, token, {
        autoSubscribe: true,
      } as RoomConnectOptions);

      // Publish the mic track
      const micTrack = await createLocalAudioTrack();
      await newRoom.localParticipant.publishTrack(micTrack);
      setMicOn(true);

      setRoom(newRoom);
    } catch (err: any) {
      console.error(err);
      setStatus("disconnected");
      setError(err.message ?? "Unknown error");
    }
  }

  const endConversation = () => {
    if (!room) return;
    room.disconnect();
    setRoom(null);
    setMicOn(false);
    setStatus("disconnected");
  }

  return (
    <main className="flex flex-col items-center justify-center min-h-screen gap-6 p-6">
      <h1 className="text-2xl font-bold">AI Voice Conversation (真人語音)</h1>

      {/* Connection Status */}
      <div className="text-lg font-medium">
        Status:
        {status === "connected" && (
          <span className="text-green-600 ml-2">Connected</span>
        )}
        {status === "connecting" && (
          <span className="text-yellow-600 ml-2">Connecting...</span>
        )}
        {status === "disconnected" && (
          <span className="text-red-600 ml-2">Disconnected</span>
        )}
        {status === "idle" && (
          <span className="text-gray-500 ml-2">Idle</span>
        )}
      </div>

      {/* Mic Indicator */}
      <div>
        Mic:
        <span className={micOn ? "text-green-600" : "text-red-600"}>
          {micOn ? " ON" : " OFF"}
        </span>
      </div>

      {/* Hidden Audio Element for AI playback */}
      <audio ref={audioRef} autoPlay playsInline />

      {/* Error */}
      {error && <p className="text-red-500">{error}</p>}

      {/* Buttons */}
      {status !== "connected" ? (
        <button
          onClick={startConversation}
          className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 cursor-pointer"
        >
          Start Conversation
        </button>
      ) : (
        <button
          onClick={endConversation}
          className="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700 cursor-pointer"
        >
          End Conversation
        </button>
      )}
    </main>
  );
}
